Split the class and feat prerequisite ignore into two separate settin…
cabarius/ToyBox pull request #606
Opened 2021-12-12 15:47 UTC by nihilistzsche

…gs so that classes can be unlocked but feats still filtered.  #605.

2021-12-13 05:16 UTC, cabarius commented
It looks like this was not properly rebased with master.  Please rebase so we don't lose more recent updates.

2021-12-13 05:18 UTC, cabarius requested changes
Please rebase against master so we don't lose my more recent changes.

2021-12-13 05:18 UTC, cabarius commented on ToyBox/ReadMe.md
> -    * Mouse3 Camera + forward/back keys now lets you fly freely when pitch is enabled
Why is this being removed?

2021-12-13 05:18 UTC, cabarius commented on ToyBox/classes/Models/Settings.cs
> -        public bool toggleCameraElevation = false;
these changes should not be deleted.  Please rebase and and apply your patch to top of tree.

2021-12-13 10:50 UTC, nihilistzsche commented
Hi, I tried to rebase it to master but when I go to rebase it appears in my history to already be on top of current master.   Is there another change missing from the repo?

2021-12-15 20:17 UTC, cabarius approved these changes

2021-12-15 20:17 UTC, merged

2021-12-15 20:23 UTC, cabarius commented
I merged this and it turned out to be wrong.  I am reverting this patch.  Please check out master and apply just the changes you made to top of tree.