Hide unimportant loot
cabarius/ToyBox pull request #787
Opened 2023-03-27 00:55 UTC by xADDBx

This feature is experimental (and I don't know if it's really needed either).
This allows you to select a rarity in the options. It checks loot markers on your map. If they don't contain an item exceeding your chosen rarity then the map markers of the loot container will be hidden. UI:
![grafik](https://user-images.githubusercontent.com/62178123/227816180-469e65f5-d54b-482a-aa5f-2256cf9f80e7.png)

I didn't get to test much, but here's what I found until now:
- It seems to work for normal map markers and the ones discovered using the Reveal Loot option
- It does not seem to remove enemy loot containers (which are only shown when in vicinity or hovering over them with the lens, basically their vanilla behavior). I don't really know why? I'm using
`var interactionLootParts = Game.Instance.State.MapObjects.All
                .Where<EntityDataBase>(e => e.IsInGame)
                .Select<EntityDataBase, InteractionLootPart>(i => i.Get<InteractionLootPart>())
                .Where<InteractionLootPart>(i => i?.Loot != Game.Instance.Player.SharedStash)
                .NotNull<InteractionLootPart>();` (copied from the reveal ground loot)
to get the markers when updating by button. So I'd guess it's not an InteractionLootPart then?
- When enemies are killed with a critical hit the marker is, like with normal enemy containers, not hidden. Different from normal enemy containers, the containers will be visible even if not in vicinity of them

On an actual map:
No filterting:
![grafik](https://user-images.githubusercontent.com/62178123/227816721-5fdb8e6a-9092-4286-8abf-998a1ba17b7e.png)
Hidden up to epic:
![grafik](https://user-images.githubusercontent.com/62178123/227816804-ee0c45ed-9495-487c-ad99-ea43b6424c04.png)

While not exactly the same, this should be close enough to Close #759.

2023-03-27 03:32 UTC, cabarius approved these changes

2023-03-28 21:02 UTC, cabarius requested changes

2023-03-28 21:02 UTC, cabarius commented on ToyBox/classes/Infrastructure/ItemRarity.cs
> +        public static void Hide(this LocalMapLootMarkerPCView localMapLootMarkerPCView) {
Please add comments explaining what this is doing and how

2023-03-28 21:02 UTC, cabarius commented on ToyBox/classes/Infrastructure/LootHelper.cs
> +            var MarksLoot = SceneManager.GetSceneByName("UI_Ingame_Scene").GetRootGameObjects()[1].findChild("InGameStaticPartPCView")
please add a comment explaining this

2023-03-28 21:20 UTC, ArcaneTrixter commented on ToyBox/classes/Infrastructure/LootHelper.cs
> +            var MarksLoot = SceneManager.GetSceneByName("UI_Ingame_Scene").GetRootGameObjects()[1].findChild("InGameStaticPartPCView")
Is there any reason you're not using the `/` syntax here instead? e.g. "InGameStaticPartPCView/StaticCanvas/ServiceWindowsPCView/Background/Windows/LocalMapPCView/ContentGroup/MapBlock/Map/MarksLoot"?

2023-03-28 22:04 UTC, cabarius approved these changes

2023-03-28 22:05 UTC, merged